services:
  - type: web
    name: mindfeed
    runtime: static
    buildCommand: npm ci && node scripts/set-env.js && npm run build -- --configuration=production
    envVars:
      - key: GUARDIAN_API_KEY
        sync: false
    staticPublishPath: dist/mindfeed/browser
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
