// ⚠️  AUTO-GENERATED by scripts/set-env.js — do not edit manually.
// Source: GUARDIAN_API_KEY environment variable injected at build time.
export const environment = {
  production: true,
  guardianApiKey: '',
  rss2jsonApiUrl: 'https://api.rss2json.com/v1/api.json',
  pubmedEmail: 'mindfeed@example.com',
  useDynamicNews: false,
};
