/**
 * Pre-build script: injects environment variables into Angular environment files.
 * Run automatically via npm `prebuild` lifecycle hook before `ng build`.
 *
 * Required env vars:
 *   GUARDIAN_API_KEY  – The Guardian Open Platform developer key
 *                       https://open-platform.theguardian.com/access/
 */

const fs   = require('fs');
const path = require('path');

const PROD_ENV = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

const guardianKey    = process.env.GUARDIAN_API_KEY || '';
const useDynamicNews = guardianKey.length > 0;

const content = `// ⚠️  AUTO-GENERATED by scripts/set-env.js — do not edit manually.
// Source: GUARDIAN_API_KEY environment variable injected at build time.
export const environment = {
  production: true,
  guardianApiKey: '${guardianKey}',
  rss2jsonApiUrl: 'https://api.rss2json.com/v1/api.json',
  pubmedEmail: 'mindfeed@example.com',
  useDynamicNews: ${useDynamicNews},
};
`;

fs.writeFileSync(PROD_ENV, content, 'utf8');

const maskedKey = guardianKey.length > 8
  ? `${guardianKey.slice(0, 8)}${'*'.repeat(guardianKey.length - 8)}`
  : guardianKey.length > 0
    ? guardianKey
    : '(not set – falling back to static articles)';

console.log(`✅  set-env.js → environment.prod.ts written`);
console.log(`    GUARDIAN_API_KEY = ${maskedKey}`);
console.log(`    useDynamicNews   = ${useDynamicNews}`);
